# Core
spring:
  application:
    name: hotels
  profiles.active: local
  main:
    web-environment: true

  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES


---
spring:
  profiles: local

  hotels:
    rateLimit: 10
---
spring:
  profiles: production
  hotels:
    rateLimit: 10